
server:
  port : 8085


spring:
  application:
    name : accommodation
  datasource:
    url : jdbc:mysql://localhost:3306/pg_accommodation_db?createDatabaseIfNotExist=true
    username : root
    password : root@39
  jpa:
    show-sql : true
    hibernate:
      ddl-auto =:update

      
springdoc:
  swagger-ui:
    path: /swagger-ui.html